<?php
acf_add_local_field_group( array(
	'key'                   => 'group_5bf3e14074a22',
	'title'                 => 'Alert Bar',
	'fields'                => array(
		array(
			'key'               => 'field_5bf3e1499447c',
			'label'             => 'CTA',
			'name'              => 'cta',
			'type'              => 'link',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'return_format'     => 'array',
		),
		array(
			'key'               => 'field_5bf3e2459447e',
			'label'             => 'Type',
			'name'              => 'type',
			'type'              => 'radio',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'header' => 'Header',
				'footer' => 'Footer',
			),
			'allow_null'        => 0,
			'other_choice'      => 0,
			'default_value'     => 'header',
			'layout'            => 'horizontal',
			'return_format'     => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key'               => 'field_5bf3e2569447f',
			'label'             => 'Is Sticky?',
			'name'              => 'sticky',
			'type'              => 'true_false',
			'instructions'      => 'Makes the bar stick to the top or bottom of the screen when scrolling',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'message'           => '',
			'default_value'     => 0,
			'ui'                => 0,
			'ui_on_text'        => '',
			'ui_off_text'       => '',
		),
	),
	'location'              => array(
		array(
			array(
				'param'    => 'post_type',
				'operator' => '==',
				'value'    =>  $post_type,
			),
		),
	),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen'        => '',
	'active'                => 1,
	'description'           => '',
) );
